services:
  frontend:
    image: itassets-frontend:latest
    hostname: frontend
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "./ssl/domain.crt:/srv/ssl/fullchain.pem:ro"
      - "./ssl/domain.key:/srv/ssl/privkey.pem:ro"
    networks:
      - itassets
    logging: 
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"
    build: 
      context: ./frontend
      tags:
        - "itassets-frontend:latest"

  backend:
    image: itassets-backend:latest
    hostname: backend
    networks:
      - itassets
    env_file: "./environment/dev_backend.env"
    logging: 
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"
    build: 
      context: ./backend
      tags:
        - "itassets-backend:latest"
  
  upload_coordinator:
    image: uploader-coordinator:latest
    hostname: coordinator
    networks:
      - itassets
    env_file: "./environment/dev_coordinator.env"
    logging:
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"
    build: 
      context: ./upload_coordinator
      tags:
        - "upload-coordinator:latest"

networks:
  itassets: