services:
  frontend:
    image: itassets-frontend:latest
    hostname: frontend
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "./ssl/domain.crt:/srv/ssl/fullchain.pem:ro"
      - "./ssl/domain.key:/srv/ssl/privkey.pem:ro"
    networks:
      - itassets
    depends_on: 
      - backend
      - upload_coordinator
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: 
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"
    build: 
      context: ./frontend
      tags:
        - "itassets-frontend:latest"

  backend:
    image: itassets-backend:latest
    hostname: backend
    networks:
      - itassets
    depends_on: 
      - upload_coordinator
    env_file: "./environment/dev_backend.env"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/auth"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: 
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"
    build: 
      context: ./backend
      tags:
        - "itassets-backend:latest"
  
  upload_coordinator:
    image: uploader-coordinator:latest
    hostname: coordinator
    networks:
      - itassets
    depends_on: 
      - mssql
    env_file: "./environment/dev_coordinator.env"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging:
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"
    build: 
      context: ./upload_coordinator
      tags:
        - "upload-coordinator:latest"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: mssql
    networks:
      - itassets
    container_name: mssql
    volumes:
      - ./sql:/mnt/mssql_data:rw
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test1234
      - MSSQL_PID=Express
      - MSSQL_DATA_DIR=/mnt/mssql_data
    restart: always
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S localhost", "-U", "sa", '-P', 'Test1234']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: 
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"

networks:
  itassets: