apiVersion: v1
kind: Service
metadata:
  name: itassets-backend-service
spec:
  selector:
    app: itassets-backend
  ports:
  - name: backend-port
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  clusterIP: None