apiVersion: apps/v1
kind: Deployment
metadata:
  name: itassets-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itassets-frontend
  template:
    metadata:
      labels:
        app: itassets-frontend
    spec:
      imagePullSecrets:
      - name: itassets-registry
      containers:
      - name: itassets-frontend
        image: aegisitcontainers.azurecr.io/aiscorp/itassets-frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: frontend-http
          containerPort: 80
          protocol: TCP
        - name: frontend-https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: ssl
          mountPath: /srv/ssl/
          readOnly: true
        # Keepalive
        livenessProbe:
          httpGet:
            port: 443
            path: /
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 443
            path: /
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: ssl
        secret:
          secretName: frontend-tls-secrets
          items:
            - key: tls.crt
              path: fullchain.pem
            - key: tls.key
              path: privkey.pem