apiVersion: v1
kind: Service
metadata:
  name: itassets-frontend-service
spec:
  selector:
    app: itassets-frontend
  ports:
  - name: frontend-http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: frontend-https
    port: 443
    targetPort: 443
    protocol: TCP
  type: LoadBalancer