apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data-volume
spec:
  accessModes: 
  - ReadWriteOnce
  capacity: 
    storage: 4Gi
  hostPath:
    path: /run/desktop/mnt/host/c/Users/asheeran/Development/ITAssets/sql/
  storageClassName: ""