apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  replicas: 1
  serviceName: mariadb-service
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      containers:
      - name: mariadb
        image: mariadb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: mariadb-port
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        env:
          - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
            value: "0"
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: DB_PASS
          - name: MYSQL_INITDB_SKIP_TZINFO
            value: "1"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mariadb-data