apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: mariadb-data-volume
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
