name: Test Building Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy .env files
      run: cp ./environment/prod_frontend.env ./frontend/.env.production
    - name: Build the Docker Compose
      working-directory: ./backend
      run: docker compose build
