on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - name: Build the Docker image
      working-directory: ./backend
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY_URL }}/aiscorp/itassets-backend:v$TIMESTAMP
    - name: Push the Docker Image
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/aiscorp/itassets-backend:v$TIMESTAMP
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - name: Build the Docker image
      working-directory: ./backend
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY_URL }}/aiscorp/itassets-frontend:v$TIMESTAMP
    - name: Push the Docker Image
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/aiscorp/itassets-frontend:v$TIMESTAMP
